site_name: "せかすと公式うぃき"
copyright: Copyright &copy; 2021 Second Story

theme:
  name: material
  language: ja
  favicon: img/favicon.png
  logo: img/logo.png
  palette:
    primary: light green
    accent: light green
  features:
    - navigation.sections
    - toc.integrate

markdown_extensions:
  - toc:
      permalink: true

plugins:
  - search:
      lang: ja

nav:
  - "ようこそ": index.md
  - "ウェブサイト": website.md
  - "コマンド":
    - "チャット /chat": command/chat.md